list_manager:
  list_storage_folder: ./lists
  generated_lists:
    allowlist: pv-custom-allowlist.txt
    blocklist: pv-custom-blocklist.txt
  block_sources:
    - { name: 'block1', source: 'http://www.example.com', enabled: true}
    - { name: 'block2', source: 'http://www.github.com', enabled: false}
    - { name: 'block3', source: 'http://www.source.com', enabled: true}
  allow_sources:
    - { name: 'allow1', source: 'https://www.allow1.com'}
    - { name: 'allow2', source: 'https://www.allow2.com'}

