list_manager:
  list_storage_folder: ./lists
  generated_lists:
    allowlist: pv-customer-allowlist.txt
    blocklist: pv-custom-blocklist.txt
  block_sources:
    - { name: 'block1', source: 'http://www.example.com'}
    - { name: 'block2', source: 'http://www.github.com'}
  allow_sources:
    - source: 'https://www.allow1.com'
    - source: 'https://www.allow2.com'

