parameters:
  version: '0.1'
  cli_configuration_path: 'config/lists_config.yml'

services:
  _defaults:
    autowire: true
    #autoconfigure: true
    bind:
      string $version: '%version%'

  _instanceof:
    Symfony\Component\Console\Command\Command:
      tags: ['command']

  PvListManager\:
    lazy: true
    resource: '../src'
    exclude:
      - '../src/Enum/'
      - '../src/Json/'

  PvListManager\Application:
    public: true
    arguments:
      - !tagged command

  Symfony\Component\Filesystem\:
    resource: '%vendor_directory%/symfony/filesystem'

  symfony.Contracts.httpclient.httpclientinterface:
    class: Symfony\Component\HttpClient\CurlHttpClient

  Symfony\Contracts\HttpClient\HttpClientInterface: '@symfony.Contracts.httpclient.httpclientinterface'

  PvListManager\Service\SettingsService:
    arguments:
      $configurationFilePath: '%cli_configuration_path%'

  # PvListManager\Cli\:
  #   lazy: true
  #   resource: '../src'

  # PvListManager\Cli\Application:
  #   public: true
  #   arguments:
  #     - tags: ['not-command']
    #calls:
    #  - setDispatcher: ['@Ymir\Cli\EventDispatcher\AutowiredEventDispatcher']